<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>DriverX</AssemblyName>
    <Version>0.1.1</Version>
    <RootNamespace>DriverX.Desktop</RootNamespace>
    <ApplicationIcon>Assets\driverx.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\driverx-logo.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\translations.txt" LogicalName="DriverX.translations" /><EmbeddedResource Include="Assets\rclone.exe" LogicalName="DriverX.rclone.exe" />
  </ItemGroup>


  <ItemGroup>
    <EmbeddedResource Include="Assets\dark-icons\*.ico">
      <LogicalName>DriverX.dark.%(Filename).ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>

